### ISSUE TITLE
Feature request: support adding alt text (descriptions) to images

### ISSUE THREAD

**Issue by jmairboeck** [poetaster/harbour-tooter#38] opened 2024-07-14 18:40 UTC
Support for adding alt text to images would be good for accessibility.

**Comment by poetaster** [comment] 2024-08-21 16:43
Yes, it would! I'll have a look. It might be possible with a modification to the warning mechanism.

**Comment by poetaster** [comment] 2024-09-11 14:31
Hmm, I think this duplicates #9 but I need to check my notes ...

**Comment by poetaster** [comment] 2024-09-29 08:21
is a dupe of #9

**Closed by poetaster** 2024-09-29 08:21 UTC
